import type { ExerciseId, Phase, RPE, SessionType, SetType, Stage } from './program.types';

export interface LoggedSet {
  id: string;
  setNumber: number;
  setType: SetType;
  targetReps: number | [number, number];
  actualReps: number;
  weightKg: number;
  rpe?: RPE;
  isWarmup: boolean;
  notes?: string;
  timestamp: number;
}

export interface LoggedExercise {
  exerciseId: ExerciseId;
  sets: LoggedSet[];
}

export interface Workout {
  id: string;
  date: string; // ISO date
  timestamp: number;
  stage: Stage;
  phase: Phase;
  sessionType: SessionType;
  weekType: string;
  cycleNumber: number;
  weekInCycle: number;
  dayInWeek: number;
  exercises: LoggedExercise[];
  progressionResults?: ProgressionResult[];
  notes?: string;
  durationMinutes?: number;
}

export interface ProgressionResult {
  exerciseId: ExerciseId;
  setCategory: string;
  previousWeight: number;
  newWeight: number;
  increment: number;
  repsAchieved: number;
  rpeRating?: RPE;
  rule: string;
}

// Prescribed workout (generated by workout-prescriber)
export interface PrescribedSet {
  setType: SetType;
  targetReps: number | [number, number];
  prescribedWeightKg: number;
  isVariable?: boolean;
  executionNotes?: string;
}

export interface PrescribedExercise {
  exerciseId: ExerciseId;
  sets: PrescribedSet[];
}

export interface WarmupPrescription {
  generalWarmup: string;
  warmupSets: {
    exerciseId: ExerciseId;
    sets: { weightKg: number; reps: number }[];
  }[];
}

export interface PrescribedWorkout {
  sessionType: SessionType;
  weekType: string;
  dayLabel: string;
  exercises: PrescribedExercise[];
  warmup: WarmupPrescription;
}
